sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - |
      cargo install cargo-travis || echo "cargo-travis already installed"
      export PATH=$HOME/.cargo/bin:$PATH

# the main build
script:
  - |
      cargo build &&
      cargo test &&
      cargo doc

after_success:
# measure code coverage and upload to coveralls.io
  - cargo coveralls
